### ISSUE TITLE
Creating non-existing folders wording

### ISSUE THREAD

**Issue by martinambrus** [fabiokr/vagrant-sshfs#31]
Hi, could you please clarify the question (if this is in your plugin) when a folder does not physically exist on my host machine?

Right now it asks: *Target folder `some-folder` does not exist, create?*

Anytime I answer with **yes**, I get kicked out because "y" is actually expected but that's not in the message and it always just freaks me out after 40 seconds of waiting for machine bootup just to do it again over a 1 letter answer ;)

Thanks a million!

**Comment by fabiokr** [comment]
Hi, I'd be happy to accept a pull request!

**Comment by martinambrus** [comment]
Here it goes...

#32

**Comment by fabiokr** [comment]
Closed by #32
